import { FC } from "react";

import type { Metadata } from "next";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";

import { inter } from "@/app/fonts/fonts";

import { Navbar } from "../components/Navbar";
import "../globals.css";
import { MainProviders } from "../providers/MainProviders";
import { Layout } from "../types/layout.types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<Layout> = (props) => {
  const { children } = props;

  return (
    <html lang="en" className={inter.variable}>
      <body className="h-dvh antialiased">
        <MainProviders>
          <Navbar />
          <main className="h-[calc(100dvh-64px)]">{children}</main>
        </MainProviders>
      </body>
    </html>
  );
};

export default RootLayout;
